<?php

/**
 * HRM Module Development Checklist
 * Status: 0 = not started | 1 = under development | 2 = ready
 */
return [
    [
        'category' => 'Employee Management',
        'bn'       => 'কর্মচারী ব্যবস্থাপনা',
        'icon'     => '👤',
        'items'    => [
            ['name' => 'Employee Create',                      'status' => 2],
            ['name' => 'Employee Edit',                        'status' => 2],
            ['name' => 'Employee Delete',                      'status' => 2],
            ['name' => 'Employee ID Auto Generate',            'status' => 0],
            ['name' => 'Employee Profile',                     'status' => 1],
            ['name' => 'Employee Photo',                       'status' => 2],
            ['name' => 'Department',                           'status' => 2],
            ['name' => 'Designation',                          'status' => 1],
            ['name' => 'Branch',                               'status' => 0],
            ['name' => 'Employment Type (Permanent/Contract)', 'status' => 1],
            ['name' => 'Joining Date',                         'status' => 2],
            ['name' => 'Confirmation Date',                    'status' => 1],
            ['name' => 'Resignation Information',              'status' => 2],
            ['name' => 'Termination Information',              'status' => 0],
            ['name' => 'Document Upload (NID, Passport)',      'status' => 1],
        ],
    ],
    [
        'category' => 'Department & Designation',
        'bn'       => 'বিভাগ ও পদবী',
        'icon'     => '🏢',
        'items'    => [
            ['name' => 'Department Management',        'status' => 2],
            ['name' => 'Designation Management',       'status' => 1],
            ['name' => 'Grade Management',             'status' => 0],
            ['name' => 'Reporting Manager Assignment', 'status' => 0],
        ],
    ],
    [
        'category' => 'Attendance Management',
        'bn'       => 'উপস্থিতি ব্যবস্থাপনা',
        'icon'     => '📋',
        'items'    => [
            ['name' => 'Manual Attendance',          'status' => 2],
            ['name' => 'Biometric Machine Integration', 'status' => 2],
            ['name' => 'Mobile Attendance',          'status' => 0],
            ['name' => 'GPS Attendance',             'status' => 0],
            ['name' => 'Late Calculation',           'status' => 2],
            ['name' => 'Early Leave',                'status' => 2],
            ['name' => 'Overtime Calculation',       'status' => 2],
            ['name' => 'Shift Wise Attendance',      'status' => 2],
            ['name' => 'Attendance Correction Request', 'status' => 0],
            ['name' => 'Attendance Approval',        'status' => 0],
        ],
    ],
    [
        'category' => 'Leave Management',
        'bn'       => 'ছুটি ব্যবস্থাপনা',
        'icon'     => '🏖️',
        'items'    => [
            ['name' => 'Leave Type',             'status' => 2],
            ['name' => 'Casual Leave',           'status' => 2],
            ['name' => 'Sick Leave',             'status' => 2],
            ['name' => 'Annual Leave',           'status' => 2],
            ['name' => 'Maternity/Paternity Leave', 'status' => 2],
            ['name' => 'Leave Application',      'status' => 2],
            ['name' => 'Leave Approval',         'status' => 0],
            ['name' => 'Leave Balance',          'status' => 2],
            ['name' => 'Leave History',          'status' => 2],
        ],
    ],
    [
        'category' => 'Shift Management',
        'bn'       => 'শিফট ব্যবস্থাপনা',
        'icon'     => '🕐',
        'items'    => [
            ['name' => 'Shift Create',  'status' => 2],
            ['name' => 'Shift Assign',  'status' => 2],
            ['name' => 'Weekly Holiday', 'status' =>2],
            ['name' => 'Rotation Shift', 'status' => 0],
            ['name' => 'Night Shift',   'status' => 0],
        ],
    ],
    [
        'category' => 'Payroll',
        'bn'       => 'বেতন ব্যবস্থাপনা',
        'icon'     => '💰',
        'items'    => [
            ['name' => 'Salary Structure',    'status' => 0],
            ['name' => 'Basic Salary',        'status' => 2],
            ['name' => 'Allowances',          'status' => 1],
            ['name' => 'Deductions',          'status' => 2],
            ['name' => 'Tax Calculation',     'status' => 0],
            ['name' => 'Provident Fund',      'status' => 0],
            ['name' => 'Bonus',               'status' => 2],
            ['name' => 'Festival Bonus',      'status' => 1],
            ['name' => 'Overtime Payment',    'status' => 1],
            ['name' => 'Salary Sheet',        'status' => 1],
            ['name' => 'Payslip Generate',    'status' => 1],
            ['name' => 'Bank Transfer Report', 'status' => 0],
        ],
    ],
    [
        'category' => 'Loan & Advance',
        'bn'       => 'ঋণ ও অগ্রিম',
        'icon'     => '🏦',
        'items'    => [
            ['name' => 'Employee Loan',   'status' => 0],
            ['name' => 'Salary Advance',  'status' => 1],
            ['name' => 'EMI Deduction',   'status' => 0],
            ['name' => 'Loan Report',     'status' => 0],
        ],
    ],
    [
        'category' => 'Recruitment',
        'bn'       => 'নিয়োগ',
        'icon'     => '🎯',
        'items'    => [
            ['name' => 'Job Vacancy',          'status' => 0],
            ['name' => 'Candidate Information', 'status' => 0],
            ['name' => 'Interview Schedule',   'status' => 0],
            ['name' => 'Interview Result',     'status' => 0],
            ['name' => 'Candidate Selection',  'status' => 0],
            ['name' => 'Employee Onboarding',  'status' => 0],
        ],
    ],
    [
        'category' => 'Performance Management',
        'bn'       => 'কর্মক্ষমতা মূল্যায়ন',
        'icon'     => '📈',
        'items'    => [
            ['name' => 'KPI',                      'status' => 0],
            ['name' => 'Performance Review',       'status' => 0],
            ['name' => 'Employee Evaluation',      'status' => 0],
            ['name' => 'Promotion Recommendation', 'status' => 0],
            ['name' => 'Increment Recommendation', 'status' => 1],
        ],
    ],
    [
        'category' => 'Training',
        'bn'       => 'প্রশিক্ষণ',
        'icon'     => '📚',
        'items'    => [
            ['name' => 'Training Schedule',    'status' => 0],
            ['name' => 'Trainer Information',  'status' => 0],
            ['name' => 'Training Attendance',  'status' => 0],
            ['name' => 'Training Certificate', 'status' => 0],
        ],
    ],
    [
        'category' => 'Expense & Claims',
        'bn'       => 'ব্যয় ও দাবি',
        'icon'     => '🧾',
        'items'    => [
            ['name' => 'Employee Expense',   'status' => 0],
            ['name' => 'Travel Claim',       'status' => 0],
            ['name' => 'Medical Claim',      'status' => 0],
            ['name' => 'Approval Workflow',  'status' => 0],
        ],
    ],
    [
        'category' => 'Assets Management',
        'bn'       => 'সম্পদ ব্যবস্থাপনা',
        'icon'     => '💻',
        'items'    => [
            ['name' => 'Laptop Assignment', 'status' => 0],
            ['name' => 'Mobile Assignment', 'status' => 0],
            ['name' => 'ID Card',           'status' => 0],
            ['name' => 'Asset Return',      'status' => 0],
        ],
    ],
    [
        'category' => 'Notice Board',
        'bn'       => 'নোটিশ বোর্ড',
        'icon'     => '📌',
        'items'    => [
            ['name' => 'Company Notice', 'status' => 0],
            ['name' => 'Circular',       'status' => 0],
            ['name' => 'Holiday Notice', 'status' => 0],
        ],
    ],
    [
        'category' => 'Holiday Management',
        'bn'       => 'ছুটির দিন ব্যবস্থাপনা',
        'icon'     => '📅',
        'items'    => [
            ['name' => 'Holiday Calendar', 'status' => 2],
            ['name' => 'Public Holidays',  'status' => 2],
            ['name' => 'Weekend Setup',    'status' => 0],
        ],
    ],
    [
        'category' => 'User & Permission',
        'bn'       => 'ব্যবহারকারী ও অনুমতি',
        'icon'     => '🔐',
        'items'    => [
            ['name' => 'HR Role',                    'status' => 0],
            ['name' => 'Admin Role',                 'status' => 0],
            ['name' => 'Department Wise Permission', 'status' => 0],
            ['name' => 'Employee Self Service (ESS)', 'status' => 0],
        ],
    ],
    [
        'category' => 'Reports',
        'bn'       => 'প্রতিবেদন',
        'icon'     => '📊',
        'items'    => [
            ['name' => 'Employee Report',    'status' => 2],
            ['name' => 'Attendance Report',  'status' => 2],
            ['name' => 'Leave Report',       'status' => 2],
            ['name' => 'Salary Report',      'status' => 2],
            ['name' => 'Overtime Report',    'status' => 2],
            ['name' => 'Department Report',  'status' => 2],
            ['name' => 'Joining Report',     'status' => 2],
            ['name' => 'Resignation Report', 'status' => 0],
            ['name' => 'Payroll Summary',    'status' => 1],
        ],
    ],
    [
        'category' => 'Notifications',
        'bn'       => 'বিজ্ঞপ্তি',
        'icon'     => '🔔',
        'items'    => [
            ['name' => 'SMS Notification',    'status' => 0],
            ['name' => 'Email Notification',  'status' => 0],
            ['name' => 'In-App Notification', 'status' => 0],
        ],
    ],
    [
        'category' => 'Dashboard',
        'bn'       => 'ড্যাশবোর্ড',
        'icon'     => '🖥️',
        'items'    => [
            ['name' => 'Total Employees',     'status' => 2],
            ['name' => 'Present Employees',   'status' => 2],
            ['name' => 'Absent Employees',    'status' => 2],
            ['name' => 'Late Employees',      'status' => 2],
            ['name' => 'Upcoming Birthdays',  'status' => 2],
            ['name' => 'Upcoming Holidays',   'status' => 2],
            ['name' => 'Payroll Summary',     'status' => 2],
            ['name' => 'Leave Summary',       'status' => 2],
        ],
    ],
    [
        'category' => 'Audit Log',
        'bn'       => 'অডিট লগ',
        'icon'     => '🗒️',
        'items'    => [
            ['name' => 'User Activity Log',  'status' => 2],
            ['name' => 'Login History',      'status' => 2],
            ['name' => 'Data Change History', 'status' => 2],
        ],
    ],
    [
        'category' => 'Integration',
        'bn'       => 'ইন্টিগ্রেশন',
        'icon'     => '🔗',
        'items'    => [
            ['name' => 'Fingerprint Machine',          'status' => 2],
            ['name' => 'Face Recognition Device',      'status' => 2],
            ['name' => 'Payroll Accounting Integration', 'status' => 0],
            ['name' => 'Mobile App API',               'status' => 0],
        ],
    ],
    [
        'category' => 'Enterprise ERP (Extra)',
        'bn'       => 'এন্টারপ্রাইজ ইআরপি (অতিরিক্ত)',
        'icon'     => '🏗️',
        'items'    => [
            ['name' => 'Multi Company',             'status' => 0],
            ['name' => 'Multi Branch',              'status' => 0],
            ['name' => 'Multi Currency',            'status' => 0],
            ['name' => 'Multi Language',            'status' => 0],
            ['name' => 'Approval Workflow',         'status' => 0],
            ['name' => 'Document Management',       'status' => 0],
            ['name' => 'Digital Signature',         'status' => 0],
            ['name' => 'API Support',               'status' => 0],
            ['name' => 'Backup & Restore',          'status' => 0],
            ['name' => 'Role Based Access Control', 'status' => 0],
        ],
    ],
];
